import matplotlib.pyplot as plt
import numpy as np

def plot_betti(dir,fname):
    """
    this method plots the betti numbers (b0 and b1) from a Perseus-generated _betti.txt
    @param: directory and name of _betti.txt
    """
    betti_file = dir+"%s_betti.txt"%fname
    betti = np.loadtxt(betti_file)
    t = betti[:,0]
    b0 = betti[:,1]
    b1 = betti[:,2]
    max_count = max(np.amax(b0),np.amax(b1))

    plt.clf()
    b0, = plt.plot(t,b0,label="b0")
    b1, = plt.plot(t,b1,label="b1")
    plt.plot([128,128],[0,max_count],color='k')
    plt.legend(handles=[b0, b1])
    plt.xlabel('strength of preference')
    plt.ylabel('count')
    plt.savefig(dir+"%s_betti.png"%fname)


def plot_persdia(dir,fname):
    """
    this method plot dim-1 persistence diagram from _1.txt generated by Perseus
    @param: directory and name of XXX_1.txt)
    """
    dim1_file = dir+"%s_1.txt"%fname
    dim1 = np.loadtxt(dim1_file)
    birth = dim1[:,0]
    death = dim1[:,1]
    colors = ['green' if d==255 else '#1f77b4' for d in list(death)]
    #t = [t for t in range(np.amin(birth),np.amax(birth)+1)]
    #t = np.array(t)
    plt.clf()
    plt.scatter(birth,death,c = colors)
    plt.plot([np.amin(birth),255],[np.amin(birth),255])
    plt.xlabel('birth')
    plt.ylabel('death')
    plt.savefig(dir+"%s_persdia.png"%fname)

def plot_all(dir,fname):
    plot_betti(dir,fname)
    plot_persdia(dir,fname)

#for i in range(1,11):
#    plot_all('random'+str(i))
plot_all('/Users/jiaying/Downloads/TDA/cubical/random/','shuffle12_8184')
